In [2]:
import numpy as np
l1 = [1, 2, 3, 4, 5]
arr = np.array(l1)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

In [6]:
import numpy as np
import pandas as pd

df1 = pd.Series([1,2,3,4,5])
print(df1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
df1 = pd.DataFrame({"name":["ali","abss","zyz"],
                    "age":[25,30,np.nan]})
df1

   name   age
0   ali  25.0
1  abss  30.0
2   zyz   NaN

In [8]:
df1.shape

(3, 2)

In [9]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     2 non-null      float64
dtypes: float64(1), str(1)
memory usage: 180.0 bytes

In [10]:
df1.columns

Index(['name', 'age'], dtype='str')

In [11]:
df1.describe()

             age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [12]:
df1.iloc[:,1:2]

    age
0  25.0
1  30.0
2   NaN

In [13]:
df1.loc[:, 'age']

0    25.0
1    30.0
2     NaN
Name: age, dtype: float64

In [14]:
df1["age"]

0    25.0
1    30.0
2     NaN
Name: age, dtype: float64

In [15]:
df1.head()

   name   age
0   ali  25.0
1  abss  30.0
2   zyz   NaN

In [17]:
df1.tail(1)

  name  age
2  zyz  NaN

In [46]:
# From dictionary
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Paris', 'London']
})

# From list of dictionaries
df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30],
})

# From NumPy array
df3 = pd.DataFrame(np.random.randn(4, 3), 
                   columns=['A', 'B', 'C'],
                   index=['Row1', 'Row2', 'Row3', 'Row4'])

df2

    Name  Age
0  Alice   25
1    Bob   30

In [29]:
import numpy as np
import pandas as pd

df1 = pd.DataFrame({"name":["Ahmad", "Hamza", "Ahtesham", "Anees"],
                    "age": [20,17,22,21],
                    "qualification": ["BS.IT", "Pharm-D", "BS-CS", "Working"]})
df1

       name  age qualification
0     Ahmad   20         BS.IT
1     Hamza   17       Pharm-D
2  Ahtesham   22         BS-CS
3     Anees   21       Working

In [30]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4 non-null      str
 1   age            4 non-null      int64
 2   qualification  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [31]:
df1.describe()

             age
count   4.000000
mean   20.000000
std     2.160247
min    17.000000
25%    19.250000
50%    20.500000
75%    21.250000
max    22.000000

In [32]:
df1.columns

Index(['name', 'age', 'qualification'], dtype='str')

In [33]:
df1.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [34]:
df1.shape

(4, 3)

In [38]:
df1.iloc[:,:1]

       name
0     Ahmad
1     Hamza
2  Ahtesham
3     Anees

In [43]:
df1.loc[:, "qualification"]

0      BS.IT
1    Pharm-D
2      BS-CS
3    Working
Name: qualification, dtype: str

In [55]:
#add null value in dataframe using random numbers
df1 = pd.DataFrame(np.random.randn(50,50))
df1.iloc[1:2] = np.nan
print(df1)

          0         1         2         3         4         5         6   \
0  -0.230881 -0.634613  1.537675 -0.043761 -2.079473  0.886108 -0.212255
1        NaN       NaN       NaN       NaN       NaN       NaN       NaN
2  -0.266656 -1.475593 -0.219749 -1.411609 -0.712306 -1.328480  0.279028
3  -1.454104  0.509354 -0.141759 -0.778674 -1.748803  2.090180  0.077524
4   0.640109 -2.874225 -0.631747  0.788270 -1.802723 -1.321664  1.720046
5   0.191019  0.463457  2.137611  0.619600 -1.182162  1.364809 -0.434413
6  -0.301270  0.853429  0.054175  0.704740 -0.017681 -0.087366  0.447666
7  -0.488628 -0.447809  0.501210 -0.121180  0.470958  0.415042  0.366231
8  -0.237824 -0.615331  0.100867  0.989695  1.837263 -1.398501 -0.720019
9  -0.886360 -1.087025 -0.726011  2.077700 -0.141796 -0.114708  0.752516
10  0.644600 -0.835886 -1.143064  1.474052 -0.500626  0.012930 -2.173387
11  0.297104 -0.352350  0.537246  0.265542 -1.374416  1.429960  0.799527
12  0.595613 -0.356664 -1.144714 -0.702641  1.372986 -0.364378  0.066678
13  1.710580  0.815355 -0.084029 -1.186171  1.694071 -0.554172 -0.555662
14  1.775307 -1.587699  0.051630  1.831403 -0.543428  0.003332 -0.161613
15  1.253016 -0.065829 -0.530940 -2.497716 -1.160265 -1.090802 -0.090120
16  0.356770 -0.097100  1.139692 -0.350137  2.073827  0.379759 -0.606892
17  0.187300 -0.054273 -0.310512  0.279712 -2.264616 -0.991948  0.664466
18  0.079096  0.192684  1.010759 -0.251833 -0.083100 -0.369844 -0.206552
19  1.027186 -0.910429 -1.797253  0.587408  0.421087  2.046140  1.577532
20 -0.340332  0.885641  0.013094 -0.493774  0.372218 -0.563627  0.085744
21  0.298116 -0.101734 -0.534312 -1.102739  0.225960 -0.843983 -0.355668
22 -0.101952 -1.333916 -1.545785 -0.720086  0.372148  0.612363 -0.088944
23 -0.673975 -0.436139 -0.758027  0.566087  1.218817  0.530352  0.516917
24 -2.606449  0.931056 -1.297991  0.768902 -0.358947  0.898226 -0.590283
25  1.176790 -0.943348 -1.305422 -0.003991  0.491535  0.631990  0.854451
26 -0.060708 -0.320080 -1.302257  0.760566  0.229954  0.020498 -0.356755
27 -0.202013 -0.429274 -1.368163 -0.699042  0.174189 -0.578990  0.095028
28 -0.562564 -0.846674  0.288283  1.671113 -1.372662  1.483496  0.471477
29  0.959252 -1.140857  1.356007  0.811771 -0.181768  1.846141  0.837086
30  1.070631  0.585603  0.003915 -0.346849 -0.254112 -0.521453 -0.340064
31 -0.384281 -0.374369  1.162419  0.866139  0.786336  0.801014  1.026984
32  0.876398  1.758393 -0.248905 -0.560398 -1.440631 -0.757959 -0.112116
33  0.857327 -0.477199  0.569093  0.446852  0.537557 -1.215088  0.968921
34  0.103879 -0.896738  1.368683 -0.072133  0.598997 -0.085091  0.947378
35 -0.504514  1.270120 -0.116904 -1.664134  0.556949 -0.201530  1.952803
36 -0.634707  0.234475  0.999977  0.594393 -0.125860 -0.413352  0.840298
37  1.401228 -1.176997  1.822958 -1.302030  1.859214 -0.632598  0.247001
38 -0.023962  0.093778 -0.076163  2.330088  0.204889 -1.327084  1.087466
39 -0.955650 -1.961188  1.140428  0.720411 -0.848374 -0.685404  0.885386
40  0.005508  1.327661 -0.167644  1.702071 -1.646817 -0.596462  0.376459
41 -0.343213 -0.075691 -0.159685  1.037120  0.104187  0.114472  0.241047
42 -0.959323 -0.613577  0.032129 -0.208687  0.033790 -1.194625  2.090804
43 -0.439853  2.854784 -0.391293  0.875547  0.148480  0.629671 -0.868276
44  0.398030  0.313919 -0.222570 -0.547583  1.326671 -1.095268  0.709001
45  1.458832  0.179237 -1.038886 -0.680356 -2.327152  0.149529  0.647061
46 -0.909262  0.855374  1.717755 -0.044654  1.236168 -0.063395 -1.074449
47  0.312975 -0.821889 -0.252752  1.288352 -0.118473 -0.818295  1.999159
48 -0.002573 -1.966656  0.004708 -0.392724  0.935044  0.778669 -0.733514
49 -0.196327  0.015868 -1.364099 -0.307687  0.087454  0.510461 -0.376129

          7         8         9   ...        40        41        42        43  \
0   0.775982 -0.627054 -0.662301  ...  1.618123 -0.657199 -0.014420 -1.058179
1        NaN       NaN       NaN  ...       NaN       NaN       NaN       NaN
2   1.949034  1.443972 -0.161121  ... -0.743415 -1.447630  0.138597  0.497556
3  -0.277197 -0.657998  1.246517  ... -0.852967  1.107618  2.330657  0.817540
4  -1.100055 -0.744463  0.356467  ... -0.784886 -0.504718 -0.128805  0.068147
5   0.455805 -0.877977 -0.267551  ... -0.562922  1.675061 -1.729041  1.354443
6  -0.907170 -1.200965 -0.603814  ...  0.000855  0.605351  1.994963 -0.403712
7   0.749602  1.255586  0.241543  ...  1.371514  1.143804  1.074110 -0.488166
8   1.172109  0.479651 -0.091940  ...  0.322793 -0.282605 -0.875393 -2.895506
9   0.243338 -0.569419 -1.548524  ... -0.048460  0.158445 -0.962848  1.055567
10 -0.864140 -0.910644 -1.124146  ...  0.939366  0.144729 -0.860401 -0.182722
11 -1.145361  0.173352 -1.749899  ...  0.177398 -1.607474  1.022229  1.545512
12  0.158440 -0.608750  2.240380  ...  1.459893  0.288224 -0.709847 -1.972721
13 -0.728040 -0.283017  0.403346  ...  1.156253  1.272846  1.682127  0.917180
14 -0.700515 -0.503989  0.910888  ...  0.053654  0.295020 -1.530248  0.215877
15 -0.687037  0.376072  0.022973  ... -1.467837 -0.840421 -0.210430  0.910848
16 -0.583714 -2.219995 -0.021687  ... -0.100846  0.079395  1.671012 -0.560643
17  0.048030 -0.066676  1.212633  ...  0.779650 -0.792200 -0.592522 -0.207381
18 -1.336253 -0.330499  1.378047  ... -0.339407  0.443084 -0.622297 -2.091529
19  0.859178 -0.253029  0.253291  ... -1.355903  0.021821 -0.658909 -1.571343
20  1.203252 -0.118905 -0.327574  ... -0.664347  0.240835 -1.281124  1.944188
21  0.441189  0.276326  0.412233  ... -2.528651 -1.369330  0.395887 -0.158225
22 -0.995799 -1.094331 -1.049126  ...  1.249049 -0.064622 -1.098464  0.092402
23  1.016483 -1.115665  0.106662  ...  0.191534 -0.683755 -0.872011  1.337981
24 -1.317890  0.112035 -0.125522  ... -0.736792  0.082060 -0.231909 -0.822318
25  0.876774  1.208528  0.332733  ... -1.859004 -0.224581 -0.339015 -0.844610
26 -1.724225 -0.593419 -0.251877  ... -0.296885 -0.392365  0.289567 -0.276232
27  0.072027 -0.251380 -0.264395  ...  0.226591  2.042887 -0.418225  1.706778
28  1.275159 -1.680198  1.937679  ...  0.228582 -1.683651  0.105103 -0.843604
29 -2.516504  0.189466 -0.270548  ... -1.262762 -1.390022  0.086508  0.830785
30  0.934373 -0.590834 -0.665860  ... -1.500668 -0.499998 -0.708034  1.098741
31  0.948109 -1.610120 -0.749387  ... -1.215719 -0.188903  1.008130 -0.489524
32  0.332686 -1.159960 -0.327199  ... -0.893395  0.118403 -0.111143 -0.445955
33 -0.398716  0.015049  0.061689  ...  0.122522 -0.309856 -0.649389  0.247273
34  1.205335  0.100936  0.915712  ...  0.720931  0.617497  0.043431  0.407671
35 -0.152729  1.141603 -0.791116  ...  0.769764 -0.751745 -1.644556 -1.384247
36  0.168064 -0.814793  1.541025  ...  0.067562 -1.179533 -0.738584 -1.049707
37  1.443886 -0.164965 -0.176839  ...  0.855019 -1.266514  1.571282 -0.683400
38 -1.826378  0.484131 -0.370483  ...  2.071730  1.194736 -1.775996  1.274206
39 -0.481375 -0.472430  1.862992  ...  1.834012  0.346558 -1.820602  0.486885
40 -0.537756  1.388208 -0.337588  ...  0.832878 -0.700665  0.307866 -0.487517
41 -0.281881 -0.530540 -1.794926  ...  0.652544 -1.946305  0.287799  1.488347
42 -0.661593  2.102517 -1.127523  ...  0.518031  0.378832 -0.275097 -0.033289
43 -0.523366  0.434394  0.192504  ...  2.719111  1.010128  1.725226  1.268167
44  1.054463 -0.159670 -0.775980  ... -0.965750 -1.916484 -1.362590 -0.186580
45 -0.950452  0.413741 -1.330383  ...  0.393409 -1.261147 -1.150947  0.699255
46 -0.537337  1.307945 -0.374258  ... -1.940470 -0.599693  0.046337 -1.715394
47 -0.027182 -0.225338 -0.053077  ...  0.215031  1.012147 -0.790186  2.686272
48  1.806569 -0.689582  1.739498  ... -0.411079 -1.560459 -0.976736  0.538864
49  2.206920  0.402815  0.067732  ... -0.359282  0.170325 -0.581832  1.274483

          44        45        46        47        48        49
0  -1.090021  0.521741 -1.495391  0.946708 -0.415220  2.037125
1        NaN       NaN       NaN       NaN       NaN       NaN
2  -0.452326 -0.951650  1.831829  0.844110  0.520835 -0.923892
3   0.923351 -0.498472  1.370101  0.905669  0.534435 -0.884249
4   0.914411 -0.606923  0.252902 -1.944892 -1.868628 -0.935353
5  -0.443619 -1.017373 -1.261370 -1.383633  1.012372 -0.002338
6   1.055406  1.266309  0.286216  0.150950  1.025371  1.432070
7  -1.446953  0.086607 -0.814115 -0.271771 -0.201694 -0.172420
8  -0.586907  0.281895  0.212435  0.415730 -0.129383  0.468392
9   0.938884  1.397281 -1.054465 -0.316003 -1.120129 -1.551618
10  1.745621  0.089196  1.674859 -1.997061 -1.693790  1.703661
11  0.136071 -0.387212 -1.195858  0.919501  0.510808 -0.216617
12  0.432468  1.594767  0.529943 -0.258099 -0.046824 -0.808992
13 -0.643728  0.479812  0.676400 -0.369643  0.401557  0.357040
14  1.609688 -0.755280  1.616870 -0.515683 -1.866894  0.666542
15 -0.520883  1.704242  1.070598  1.655110  0.655569 -1.716784
16  0.500893  0.401702 -0.564970 -0.695335 -0.361846  0.363728
17  0.026900  1.068951  0.717174  1.606827 -0.166758 -1.058352
18  1.233729 -0.782506 -0.967793  0.194589  0.997538 -0.168304
19 -0.305725  0.288662 -0.950527  1.994771 -0.865802 -0.373197
20  0.119539 -0.174721 -0.320983  0.211244 -0.552458  0.553685
21 -0.624557 -1.663211 -0.993717 -1.054400  1.113121 -2.087431
22  0.517938  1.236707 -1.748627 -1.080280 -0.119095  1.059453
23 -0.700133  2.560133  1.550434 -0.313394  1.067182  0.275528
24 -1.315552  0.491515 -0.323328  0.093280  0.206942 -0.447097
25 -0.000091  3.116426 -1.489863  1.384763  0.189428 -0.716241
26 -1.353596  0.329878  0.246457 -1.093573 -1.255611 -1.892098
27 -0.660420 -0.924644 -1.097295  1.438177 -0.201658 -0.400112
28 -0.117625 -0.455228  0.537593 -0.632610  1.948839 -0.451580
29  0.194805 -1.917842 -0.925806  0.926086 -1.121292  0.325373
30 -0.091669 -1.277324 -0.376733 -1.594227  0.718813 -0.319413
31 -0.204730  1.135186  0.478346  0.659162 -1.991256  0.748141
32  1.400169  0.390214  0.604580 -0.541408 -0.798629  0.284709
33  0.026176 -0.939590  0.815480 -0.250028 -1.850099 -1.012452
34  1.099068  0.424009  0.821979 -1.771629  2.658983  0.614833
35 -3.060559 -0.502720 -0.671027 -1.054293 -0.739297  0.310196
36  1.018189  0.493670  0.303436 -0.566745 -1.008691 -1.823596
37  0.050815  2.150331  1.124336  0.339202 -0.222740 -0.934582
38  2.485977  0.684554  0.785301  0.940496 -1.173039  0.042948
39  0.553618 -1.451546 -0.331744 -0.368790  0.874863 -0.863219
40 -0.335795  0.338586  0.535289 -0.257175  0.918897  0.578214
41  0.419681 -0.218251 -0.558035 -0.354578  0.030056 -1.971037
42 -0.563993  0.777797  0.579353 -0.649690  0.585842  0.764550
43  1.042671 -0.174546 -0.781161 -2.386030  0.791430  1.220330
44 -0.070258 -1.118250  0.486187 -0.608084  0.900207 -0.230048
45  0.384053  1.167816  0.669913 -0.864132 -0.688130 -0.497662
46 -1.324411  0.578961  0.664787  0.945605 -0.703375  1.609608
47 -1.738865 -0.010267  0.152230  0.331015 -1.726206  0.663583
48 -1.253026 -0.248008 -0.283676  0.423129 -0.153784  0.326197
49 -0.432878  0.932571  1.852687 -2.256864  0.596207 -0.577059

[50 rows x 50 columns]